### ISSUE TITLE
调休和节假日能否在文字简洁上区分

### ISSUE THREAD

**Issue by wangbo-ops** [Secbone/calendar#3]
大佬，能否把调休和节假日在文字简介上进行区分？目前都是一样的，比如劳动节，调休和放假都显示为劳动节，只有颜色的区别。每天的推送不会显示颜色，不够直观。

**Comment by Secbone** [comment]
@wangbo-ops 计划加一对 🟢 和 🔴 的 emoji 在节日名前面，感觉看着有点儿傻，不过应该暂时可用。
不知道你有没有什么其他好的方案？

**Comment by wangbo-ops** [comment]
或者可以直接用汉字，放假就在后面加一个“（休）”，上班就在后面加一个“（班）”。

比如劳动节，假期就是“劳动节（休）”，上班就是“劳动节（班）”。

**Comment by wangbo-ops** [comment]
还有我发现一个奇怪的现象，如果是在Mac上订阅，是可以正常显示的。但是在iPhone（iOS 14.5.1）订阅，就无法显示具体的信息。不知道是不是两边的日历格式不一样了。
如果是这个链接的订阅地址（webcal://p48-caldav.icloud.com.cn/published/2/MTI3Njk0MTQxNzEyNzY5NFRvxM53AOH-Px17vHeUETlHRPeJkEJ3TEorSrwZB4EzH2lMOg52gxUdcROgV7ILYXmMzaLSgHOt3c1tvgN_rGs），是可以在iPhone上正常显示的，大佬可以参考一下。

**Comment by wangbo-ops** [comment]
> 还有我发现一个奇怪的现象，如果是在Mac上订阅，是可以正常显示的。但是在iPhone（iOS 14.5.1）订阅，就无法显示具体的信息。不知道是不是两边的日历格式不一样了。
> 如果是这个链接的订阅地址（webcal://p48-caldav.icloud.com.cn/published/2/MTI3Njk0MTQxNzEyNzY5NFRvxM53AOH-Px17vHeUETlHRPeJkEJ3TEorSrwZB4EzH2lMOg52gxUdcROgV7ILYXmMzaLSgHOt3c1tvgN_rGs），是可以在iPhone上正常显示的，大佬可以参考一下。

上面这个链接我发现如果是在iPhone上订阅，Mac同样没有办法同步，看来两边的订阅格式确实已经不一样了，Apple没有修复这个问题😂

**Comment by Secbone** [comment]
@wangbo-ops 我尝试更新了一下格式，你看看 iOS 是否可用？

**Comment by wangbo-ops** [comment]
> @wangbo-ops 我尝试更新了一下格式，你看看 iOS 是否可用？

大佬，iOS还是不行。

**Comment by Secbone** [comment]
@wangbo-ops _(:з」∠)_ 好吧，我再研究研究

**Comment by ueoo** [comment]
在 Mac 上订阅后，开启了 iCloud 同步，iOS 有 calendar 但不显示～

**Comment by Secbone** [comment]
iOS 同步问题到 #4 讨论吧
